### ISSUE TITLE
map 화면에서 런타임 에러

### ISSUE THREAD

**Issue by eunkyeng** [tmax-cloud/t-mat-zip#3]
![image](https://user-images.githubusercontent.com/66113237/176580580-179e4918-f378-457f-b29a-cbb1b4d695ee.png)

초기화면에서 map을 눌러 /map 경로로 이동시 위와 같은 에러 발생합니다.

**Comment by ccsforever** [comment]
![image](https://user-images.githubusercontent.com/48277126/176633320-f1aa6b6e-709c-407b-ba1a-c2db16d57f4b.png)
사이트 도메인 등록이 안되어서 일듯 합니다.
